<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageId>MaterialTheming</PackageId>
		<Description>Create customized themes with the Material 3 color system.</Description>
		<Authors>Muckenbatscher</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>material-design-primary-container.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>material;theme;ui</PackageTags>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/Muckenbatscher/MaterialTheming</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Muckenbatscher/MaterialTheming</PackageProjectUrl>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
		<None Include="..\material-design-primary-container.png" Pack="true" PackagePath="\" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'netstandard2.1'">
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>
</Project>
