name: Build and Test - MaterialTheming Library

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  PROJECT: MaterialTheming
  TEST_PROJECT: MaterialTheming.Tests

jobs:
  build-test-library:
    strategy:  
      fail-fast: false
      matrix:  
        framework:
        - net48
        - net8.0
        - net10.0
        - netstandard2.1 
        os: 
        - ubuntu-latest 
        - windows-latest  
        exclude:
          - os: ubuntu-latest
            framework: net48

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT }} -p:TargetFramework=${{ matrix.framework }}
    - name: Restore (Test project)
      if: matrix.framework != 'netstandard2.1'
      run: dotnet restore ${{ env.TEST_PROJECT }} -p:TargetFramework=${{ matrix.framework }}

    - name: Build
      run: dotnet build ${{ env.PROJECT }} --no-restore --framework ${{ matrix.framework }}
    - name: Build (Test project)
      if: matrix.framework != 'netstandard2.1'
      run: dotnet build ${{ env.TEST_PROJECT }} --no-restore --framework ${{ matrix.framework }}

    - name: Test
      if: matrix.framework != 'netstandard2.1'
      run: dotnet test --project ${{ env.TEST_PROJECT }} --no-build --framework ${{ matrix.framework }}
