name: Generate Testcasese from Java implementation

on:
  workflow_dispatch: 
  push:
  schedule:
    - cron: '30 3 * * *'

env:
    TEST_GEN_REPO_NAME: Muckenbatscher/material-color-utilities-testcases-generation
    TEST_GEN_REPO_BRANCH: main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-and-pr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
        with:
          path: dotnet-repo

      - name: Checkout reference Java implementation Repository
        uses: actions/checkout@v6
        with:
          repository: ${{ env.TEST_GEN_REPO_NAME }} 
          ref: ${{ env.TEST_GEN_REPO_BRANCH }}
          path: java-repo 

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile and Run MyTest.java
        run: |
          cd java-repo/java

          echo "Downloading required dependencies..."
          curl -fSL -O https://maven.google.com/androidx/annotation/annotation-jvm/1.9.1/annotation-jvm-1.9.1.jar
          curl -fSL -O https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.45.0/error_prone_annotations-2.45.0.jar
          
          echo "Compiling MyTest.java..."
          javac -cp ".:annotation-jvm-1.9.1.jar:error_prone_annotations-2.45.0.jar" MyTest.java
          
          echo "Executing MyTest.java..."
          java -cp ".:annotation-jvm-1.9.1.jar:error_prone_annotations-2.45.0.jar" \
            MyTest "$GITHUB_WORKSPACE/dotnet-repo/MaterialTheming.Tests/KnownTestThemes"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: dotnet-repo
          branch: test-generation
          base: master
          title: "feat: Auto-generierte C# Dateien aktualisiert"
          commit-message: "feat: Update C# testcase files. Generated from Java reference implementation."
          body: |
            Automatically generated the testcases from the java reference implementation.