name: Generate Testcases from Java implementation

on:
  workflow_dispatch: 
  schedule:
    - cron: '30 3 * * *'

env:
  PR_TARGET_BRANCH_NAME: master
  PR_SOURCE_BRANCH_NAME: test-generation

jobs:
  determine-based-commit:
    runs-on: ubuntu-latest

    outputs:
      offical_commit: ${{ steps.offical_commit.outputs.sha }}

    env:
      TEST_GEN_REPO: 'Muckenbatscher/material-color-utilities-testcases-generation'
      TEST_GEN_BRANCH: 'main'
      UPSTREAM_REPO: 'material-foundation/material-color-utilities'
      UPSTREAM_BRANCH: 'main'

    steps:
      - name: Checkout Test generation repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # fetch whole history, to be able to compare and find the common commit with official repository
          repository: ${{ env.TEST_GEN_REPO }}
          ref: ${{ env.TEST_GEN_BRANCH }}

      - name: Add official remote and fetch
        run: |
          git remote add official https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch official ${{ env.UPSTREAM_BRANCH }}

      - name: Get official commit hash
        id: offical_commit
        run: |
          COMMON_SHA=$(git merge-base origin/${{ env.TEST_GEN_BRANCH }} official/${{ env.UPSTREAM_BRANCH }})
          echo "Test case generation is based on official commit: $COMMON_SHA"
          echo "sha=$COMMON_SHA" >> $GITHUB_OUTPUT

  build-java:
    runs-on: ubuntu-latest

    env:
      TEST_GEN_REPO_NAME: Muckenbatscher/material-color-utilities-testcases-generation
      TEST_GEN_REPO_BRANCH: main
      OUTPUT_PATH: ${{ github.workspace }}/generated-output
    
    steps:
      - name: Checkout Test-Generation Java repository
        uses: actions/checkout@v6
        with:
          repository: ${{ env.TEST_GEN_REPO_NAME }} 
          ref: ${{ env.TEST_GEN_REPO_BRANCH }}

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Get required Java dependencies
        run: |
          cd java
          curl -fSL -O https://maven.google.com/androidx/annotation/annotation-jvm/1.9.1/annotation-jvm-1.9.1.jar
          curl -fSL -O https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.45.0/error_prone_annotations-2.45.0.jar

      - name: Compile MyTest.java
        run: |
          cd java
          javac -cp ".:annotation-jvm-1.9.1.jar:error_prone_annotations-2.45.0.jar" MyTest.java

      - name: Run MyTest.java
        run: |
          cd java
          mkdir -p "${{ env.OUTPUT_PATH }}"

          java -cp ".:annotation-jvm-1.9.1.jar:error_prone_annotations-2.45.0.jar" \
            MyTest "${{ env.OUTPUT_PATH }}"
  
      - uses: actions/upload-artifact@v7
        with:
          name: generated-testcase-cs-files 
          path: ${{ env.OUTPUT_PATH }}
          retention-days: 1 
  
  create-refs:
    needs: 
      - determine-based-commit
      - build-java
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      TEST_THEME_DIR: MaterialTheming.Tests/KnownTestThemes

    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # fetch whole history, to be able to compare 
          ref: ${{ env.PR_TARGET_BRANCH_NAME }}
          token: ${{ secrets.GH_PAT_WORKFLOW }} # so the actions will run when pushing to the PR branch

      - name: Check for existing branch
        id: existing_branch
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.PR_SOURCE_BRANCH_NAME }}; then
            echo "Branch '${{ env.PR_SOURCE_BRANCH_NAME }}' already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Branch '${{ env.PR_SOURCE_BRANCH_NAME }}' does not exist yet."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout existing branch
        if: steps.existing_branch.outputs.exists == 'true'
        run: |
          git fetch origin ${{ env.PR_SOURCE_BRANCH_NAME }}
          git checkout -B ${{ env.PR_SOURCE_BRANCH_NAME }} origin/${{ env.PR_SOURCE_BRANCH_NAME }}

      - name: Create new branch
        if: steps.existing_branch.outputs.exists != 'true'
        run: git checkout -B ${{ env.PR_SOURCE_BRANCH_NAME }}

      - uses: actions/download-artifact@v8
        with:
          name: generated-testcase-cs-files 
          path: ${{ env.TEST_THEME_DIR }}

      - name: Update official commit hash the testcases are based on
        run: echo "${{ needs.determine-based-commit.outputs.offical_commit }}" > .official-commit-sha

      - name: Check for changes
        id: check_diff
        run: |
          git add ${{ env.TEST_THEME_DIR }}
          git add .official-commit-sha

          CHANGES=$(git diff --staged --name-only)

          if [ -z "$CHANGES" ]; then
            echo "No changes found."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected!"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Git config as github-actions
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push generated tests
        if: steps.check_diff.outputs.has_changes == 'true'
        run: |
          git commit \
            -m "Update C# testcase files. Generated from Java reference implementation." \
            -m "Based on official commit: ${{ needs.determine-based-commit.outputs.offical_commit }}"
          git push -u origin ${{ env.PR_SOURCE_BRANCH_NAME }}

  generate-pr:
    needs: create-refs
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
      
      - name: Check for existing PR
        id: existing_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_COUNT=$(gh pr list --head ${{ env.PR_SOURCE_BRANCH_NAME }} --state open --json number --jq 'length')
          if [ "$PR_COUNT" -eq "0" ]; then
            echo "No existing PR found for the branch ${{ env.PR_SOURCE_BRANCH_NAME }}."
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "Existing PR found for the branch ${{ env.PR_SOURCE_BRANCH_NAME }}."
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Check for differences in existing branch
        id: branch_diff
        if: steps.existing_pr.outputs.exists == 'false'
        run: |
          if git ls-remote --exit-code --heads origin ${{ env.PR_SOURCE_BRANCH_NAME }}; then
            echo "Branch '${{ env.PR_SOURCE_BRANCH_NAME }}' exists on remote. Fetching latest changes..."
            
            git fetch origin ${{ env.PR_TARGET_BRANCH_NAME }}
            git fetch origin ${{ env.PR_SOURCE_BRANCH_NAME }}
            
            CHANGES=$(git diff origin/${{ env.PR_TARGET_BRANCH_NAME }}..origin/${{ env.PR_SOURCE_BRANCH_NAME }} --name-only)

            if [ -z "$CHANGES" ]; then
              echo "Branch '${{ env.PR_SOURCE_BRANCH_NAME }}' is identical to '${{ env.PR_TARGET_BRANCH_NAME }}'."
              echo "has_diff=false" >> $GITHUB_OUTPUT
            else
              echo "Branch '${{ env.PR_SOURCE_BRANCH_NAME }}' has differences to '${{ env.PR_TARGET_BRANCH_NAME }}'."
              echo "has_diff=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "Branch '${{ env.PR_SOURCE_BRANCH_NAME }}' does not exist on remote."
            echo "has_diff=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.existing_pr.outputs.exists == 'false' && steps.branch_diff.outputs.has_diff == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_WORKFLOW }}
        run: |
          gh pr create \
            --base ${{ env.PR_TARGET_BRANCH_NAME }} \
            --head ${{ env.PR_SOURCE_BRANCH_NAME }} \
            --title "Updated autogenerated testcases" \
            --body "Automatically generated the testcases from the java reference implementation." \
            --assignee "@me" \
            --label "test-generation"
