name: Publish NuGet packages

on:
  release:
    types:
      - published
      
env:
  PACKAGES_ARTIFACT: nuget-package-${{ github.event.release.tag_name }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Check Version Format in Tag
      uses: matt-usurp/validate-semver@v3
      id: version
      with:
        version: ${{ github.event.release.tag_name }}
        
  build-package:
    needs: version 
    runs-on: windows-latest
    
    strategy:
      matrix:
        project: 
          - name: MaterialTheming
            path: 'MaterialTheming/MaterialTheming.csproj'

    env:
      VERSION: ${{ needs.version.outputs.version }} 
      OUTDIR: 'PackageBuild'

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore project dependencies
      run: dotnet restore ${{ matrix.project.path }}

    - name: Build package file
      shell: pwsh
      run: |
        dotnet pack ${{ matrix.project.path }} --no-restore `
          -c Release -o ${{ env.OUTDIR }} `
          -p:PackageVersion=${{ env.VERSION }}

    - name: Upload built packages as artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.PACKAGES_ARTIFACT }}-${{ matrix.project.name }}
        path: ${{ env.OUTDIR }}/*.nupkg
        retention-days: 1

  upload-release-asset:
    needs: 
      - version
      - build-package
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    env:
      PACKAGE_DIR: 'packages'

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: ${{ env.PACKAGE_DIR }}
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.PACKAGE_DIR }}/**/*.nupkg

  publish-package:
    needs: 
      - version
      - build-package
    runs-on: ubuntu-latest
            
    permissions:
      packages: write

    env:
      PACKAGE_DIR: 'packages'

    steps:
    - uses: actions/download-artifact@v8
      with:
        path: ${{ env.PACKAGE_DIR }}

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Push all to GitHub Packages
      run: |
        for f in ${{ env.PACKAGE_DIR }}/**/*.nupkg
        do
          echo "Pushing $f to GitHub Packages source..."
          dotnet nuget push "$f" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }} 
        done

    - name: Push all to NuGet.org
      env:
        API_KEY: ${{ secrets.MATERIAL_THEMING_NUGET_KEY }}
      run: |
        for f in ${{ env.PACKAGE_DIR }}/**/*.nupkg
        do
          echo "Pushing $f to NuGet.org source..."
          dotnet nuget push "$f" \
            --source "nuget.org" \
            --api-key ${{ env.API_KEY }}
        done
